---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cra-pipeline
spec:
  workspaces:
  - name: shared-data
  - name: pipeline-secrets
  - name: artifacts

  tasks:
  - name: clone-repo
    taskRef:
      name: clone-repo
    params:
      - name: continuous-delivery-context-secret
        value: "secure-properties"
      - name: ibmcloud-apikey-secret-key
        value: "apikey"
      - name: repository
        value: $(params.repository)
      - name: branch
        value: $(params.branch)
      - name: revision
        value: $(params.revision)
      - name: pipeline-debug
        value: $(params.pipeline-debug)
    workspaces:
      - name: output
        workspace: artifacts
  - name: cra-terraform-scan
    when:
      - input: "$(params.tf-dir)"
        operator: notin
        values: [""]
    runAfter:
      - clone-repo
    workspaces:
    - name: artifacts
      workspace: shared-data
    - name: secrets
      workspace: pipeline-secrets
    taskRef:
      name: cra-terraform-scan
    params:
      - name: repository
        value: $(params.repository)
      - name: branch
        value: $(params.branch)
      - name: tf-dir
        value: $(params.tf-dir)
      - name: revision
        value: $(params.revision)
      - name: directory-name
        value: ""
      - name: pipeline-debug
        value: $(params.pipeline-debug)
    
 
    
  
