---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cra-pipeline
spec:
  workspaces:
  - name: shared-data
  - name: pipeline-secrets
  - name: artifacts

  tasks:
  - name: clone-repo
    workspaces:
    - name: artifacts
      workspace: shared-data
    taskRef:
      name: clone-repo 
  - name: cra-terraform-scan
    when:
      - input: "$(params.tf-dir)"
        operator: notin
        values: [""]
    workspaces:
    - name: artifacts
      workspace: shared-data
    - name: secrets
      workspace: pipeline-secrets
    taskRef:
      name: cra-terraform-scan
    params:
      - name: repository
          value: https://github.com/slzone/terraform-hpcs-module
        - name: branch
          value: $(params.branch)
        - name: tf-dir
          value: $(params.tf-dir)
        - name: directory-name
          value: ""
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    runAfter:
    - clone-patterns-repo
 
    
  
