---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cra-template
spec:
  spec:
  params:
    - name: repository
      description: The Git Repository for the Application Source Code. If empty, the Repository url will be found from toolchain
    - name: branch
      description: The Branch for the Application Source Code
      default: "master"
    - name: revision
      description: The Revision for the Application Source Code
      default: ""   
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"      
    - name: pipeline-debug
      default: ""
    - name: apikey
      description: The IBM Cloud API Key
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tekton-catalog-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - # secret
      apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: tekton-catalog-$(uid)
      spec:
        pipelineRef:
          name: cra-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pipeline-debug
            description: toggles debug mode for the pipeline
            default: "1"
          - name: scm-type
            description: source code type used (github, github-ent)
            default: "github"
          - name: apikey
            value: $(params.apikey)
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: tekton-catalog-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: trigger-binding-manual
      template:
        name: cra-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-ent-commit
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-id
      value: $(event.after)
    - name: commit-timestamp
      value: $(event.repository.pushed_at)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github-ent"
---        
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-ent-commit
spec:
  triggers:
    - bindings: 
        - name: github-ent-commit   
      template:
        name: cra-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-timestamp
      value: $(event.repository.updated_at)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - bindings:  
        - name: github-commit   
      template:
        name: cra-template
