---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cra-pipeline
spec:
  workspaces:
  - name: shared-data
  - name: pipeline-secrets
  - name: artifacts

  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: clone-repo
      taskRef:
        name: clone-repo
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)  
      workspaces:
        - name: output
          workspace: artifacts
    - name: artifacts
      taskRef:
        name: clone-repo
    - name: cra-terraform-scan
      when:
        - input: "$(params.tf-dir)"
          operator: notin
          values: [""]
      runAfter:
        -clone-repo
      workspaces:
    - name: artifacts
      workspace: shared-data
    - name: secrets
      workspace: pipeline-secrets
      taskRef:
        name: cra-terraform-scan
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: tf-dir
          value: $(params.tf-dir)
        - name: directory-name
          value: ""
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    
